version: '1.0'
stages:
  - prepare
  - prewallet
  - wallet
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: 'DavoineNils/jhale-computational-workflows-homework'
    revision: 'main'
    git: github
    stage: prepare
  build_after_my_tests:
    title: Building Go Docker Image
    type: build
    stage: 'prewallet'
    image_name: nilsdavoine/python3-minimal
    working_directory: '.'
    tag: 'master'
    dockerfile: Dockerfile
  run_my_tests_inside_image:
    title: Running Unit tests inside App image
    stage: 'wallet'
    image: nilsdavoine/python3-minimal
    working_directory: '.'
    commands:
      - py.test-3   
